-- =====================================================================
-- FILALIVRE — Modelo de dados (referência)
-- =====================================================================
-- O backend usa Spring Boot + JPA/Hibernate com banco H2 em modo arquivo.
-- As tabelas abaixo são criadas AUTOMATICAMENTE pelo Hibernate
-- (spring.jpa.hibernate.ddl-auto=update) ao iniciar a aplicação.
--
-- Localização do arquivo do banco: database/filalivre.mv.db
-- Este script serve como documentação oficial do esquema.
-- =====================================================================

CREATE TABLE usuarios (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome     VARCHAR(255) NOT NULL,
  email    VARCHAR(255) NOT NULL UNIQUE,
  senha    VARCHAR(255) NOT NULL,          -- hash BCrypt
  perfil   VARCHAR(255) NOT NULL,          -- OPERADOR | SUPERVISOR | GERENTE | ADMINISTRADOR
  ativo    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE caixas (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero             INTEGER NOT NULL UNIQUE,
  status             VARCHAR(255) NOT NULL, -- NORMAL | AGUARDANDO | SOLICITACAO | APROVACAO
  valor_compra       DECIMAL(12,2) NOT NULL DEFAULT 0,
  qtd_itens          INTEGER NOT NULL DEFAULT 0,
  operador_id        BIGINT,                -- FK usuarios.id (operador atual, opcional)
  inicio_atendimento TIMESTAMP,
  CONSTRAINT fk_caixa_operador FOREIGN KEY (operador_id) REFERENCES usuarios (id)
);

CREATE TABLE solicitacoes (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caixa_id      BIGINT NOT NULL,
  operador_id   BIGINT NOT NULL,
  tipo          VARCHAR(255) NOT NULL,      -- CANCELAMENTO | DESCONTO | CUPOM
  produto       VARCHAR(255) NOT NULL,
  quantidade    INTEGER,
  valor         DECIMAL(12,2),
  motivo        VARCHAR(500),
  status        VARCHAR(255) NOT NULL DEFAULT 'PENDENTE', -- PENDENTE | APROVADA | RECUSADA
  criado_em     TIMESTAMP NOT NULL,
  decidido_em   TIMESTAMP,
  decidido_por  BIGINT,                     -- FK usuarios.id (gestor que decidiu)
  CONSTRAINT fk_sol_caixa    FOREIGN KEY (caixa_id)     REFERENCES caixas (id),
  CONSTRAINT fk_sol_operador FOREIGN KEY (operador_id)  REFERENCES usuarios (id),
  CONSTRAINT fk_sol_gestor   FOREIGN KEY (decidido_por) REFERENCES usuarios (id)
);

CREATE TABLE registros_acao (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id   BIGINT NOT NULL,
  caixa_numero INTEGER,
  acao         VARCHAR(255) NOT NULL,       -- LOGIN, SOLICITACAO_CRIADA, SOLICITACAO_APROVADA, ...
  detalhes     VARCHAR(500),
  momento      TIMESTAMP NOT NULL,
  CONSTRAINT fk_reg_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- =====================================================================
-- Dados iniciais (criados automaticamente pelo DadosIniciais.java):
--   admin@filalivre.com    / admin123     (ADMINISTRADOR)
--   gerente@filalivre.com  / gerente123   (GERENTE)
--   operador@filalivre.com / operador123  (OPERADOR)
--   Caixas numerados de 1 a 6 com status NORMAL
-- =====================================================================
